### ISSUE TITLE
First instance of CONSERT IDE

### ISSUE THREAD

**Issue by asorici** [ami-lab/CONSERT-IDE#5]
## WHY
In order to define a roadmap for CONSERT IDE development we need a bare-bones starting point. The bare-bones version must be capable of creating a new project, viewing/editing new ContextEntities and ContextAssertions.

## WHAT
  - [x] Ability to create new / load exiting CONSERT Project. First iteration can use simple XML/JSON export as persistence method
  - [x] Add a tree view (in left side pannel) to view ContextEntities and ContextAssertions
  - [x] Contain a tabbed view in the central editor pannel, allowing a switch between a form view and a text view of the created ContextEntities and ContextAssertions
