### ISSUE TITLE
Add functionality to view/edit ContextEntities and ContextAssertions

### ISSUE THREAD

**Issue by asorici** [ami-lab/CONSERT-IDE#7]
## WHY
Following plan in #5 we need to be able to view/edit the details of ContextEntities and ContextAssertions defined in a CONSERT project.

## WHAT
  - [x] a tabbed panel is created that can switch between Form View, Text Editor View
  - [x] the text editor view displays the serialization (in JSON or XML format) **only for the selected ContextEntity or ContextAssertion**
  - [x] every change in the form or the text view must be reflected in the other

## NOTES
For initial implementation ContextEntities and ContextAssertions are backed up by simple POJO classes:
  - ContextEntity contains getter/setter for name and comment
  - ContextAssertion contains getter/setter for name, comment, arity and List<ContextEntities> of entities

**Comment by AlinGabriel** [comment]
done for entities, now working on for assertions.

**Comment by AlinGabriel** [comment]
Working on implementation of saving option
